/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppLembretesRouteImport } from './routes/app.lembretes'
import { Route as AppGastosRouteImport } from './routes/app.gastos'
import { Route as AppEstoqueRouteImport } from './routes/app.estoque'
import { Route as AppEscanearRouteImport } from './routes/app.escanear'
import { Route as AppCasasRouteImport } from './routes/app.casas'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppLembretesRoute = AppLembretesRouteImport.update({
  id: '/lembretes',
  path: '/lembretes',
  getParentRoute: () => AppRoute,
} as any)
const AppGastosRoute = AppGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppEscanearRoute = AppEscanearRouteImport.update({
  id: '/escanear',
  path: '/escanear',
  getParentRoute: () => AppRoute,
} as any)
const AppCasasRoute = AppCasasRouteImport.update({
  id: '/casas',
  path: '/casas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/casas': typeof AppCasasRoute
  '/app/escanear': typeof AppEscanearRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/gastos': typeof AppGastosRoute
  '/app/lembretes': typeof AppLembretesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/casas': typeof AppCasasRoute
  '/app/escanear': typeof AppEscanearRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/gastos': typeof AppGastosRoute
  '/app/lembretes': typeof AppLembretesRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/casas': typeof AppCasasRoute
  '/app/escanear': typeof AppEscanearRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/gastos': typeof AppGastosRoute
  '/app/lembretes': typeof AppLembretesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/casas'
    | '/app/escanear'
    | '/app/estoque'
    | '/app/gastos'
    | '/app/lembretes'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/casas'
    | '/app/escanear'
    | '/app/estoque'
    | '/app/gastos'
    | '/app/lembretes'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/casas'
    | '/app/escanear'
    | '/app/estoque'
    | '/app/gastos'
    | '/app/lembretes'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lembretes': {
      id: '/app/lembretes'
      path: '/lembretes'
      fullPath: '/app/lembretes'
      preLoaderRoute: typeof AppLembretesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gastos': {
      id: '/app/gastos'
      path: '/gastos'
      fullPath: '/app/gastos'
      preLoaderRoute: typeof AppGastosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque': {
      id: '/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/escanear': {
      id: '/app/escanear'
      path: '/escanear'
      fullPath: '/app/escanear'
      preLoaderRoute: typeof AppEscanearRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/casas': {
      id: '/app/casas'
      path: '/casas'
      fullPath: '/app/casas'
      preLoaderRoute: typeof AppCasasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCasasRoute: typeof AppCasasRoute
  AppEscanearRoute: typeof AppEscanearRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppGastosRoute: typeof AppGastosRoute
  AppLembretesRoute: typeof AppLembretesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCasasRoute: AppCasasRoute,
  AppEscanearRoute: AppEscanearRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppGastosRoute: AppGastosRoute,
  AppLembretesRoute: AppLembretesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
